### ISSUE TITLE
Remove redundant GitHub action workflow

### ISSUE THREAD

**Issue by hellkite500** [NOAA-OWP/ngen-cal#42] opened 2022-12-09 14:19 UTC
There are two GitHub action workflow files that essentially do the same thing -- running unit tests for the package.  We need to pick one to use and remove the other so we aren't running the tests twice.

**Comment by aaraney** [comment] 2022-12-09 14:23
Duplicate of #35?

**Closed** 2022-12-09 16:44 UTC
